### ISSUE TITLE
With last spigot update plugin didnt work.

### ISSUE THREAD

**Issue by 2xMJet** [TheDutchMC/SkinFixer#1]
Hello! After recent spigot update i got error in console when logged in and plugin didnt work.
```
[13:43:40] [Craft Scheduler Thread - 8/WARN]: [SkinFixer] Plugin SkinFixer v1.0 generated an exception while executing task 45
org.json.JSONException: JSONObject["data"] not found.
	at org.json.JSONObject.get(JSONObject.java:572) ~[?:?]
	at nl.thedutchmc.SkinFixer.changeSkin.SkinChangeOrchestrator$1.run(SkinChangeOrchestrator.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar:git-Spigot-379750e-9a9c223]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.2.jar:git-Spigot-379750e-9a9c223]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_192]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
```
 - OS: Windows 10
Java 8 update 192
Spigot 1.16.2 (git-Spigot-379750e-9a9c223)

**Comment by TheDutchMC** [comment]
Confirmed! I'll work on a patch today! Thank you for reporting the issue :D

**Comment by TheDutchMC** [comment]
I recompiled it, tested it fully, it now should work. Releases as [1.0.1](https://github.com/TheDutchMC/SkinFixer/releases/tag/1.0.1)
