### ISSUE TITLE
Everytime i try to change my skin in console i get this messagle displayed, any help?

### ISSUE THREAD

**Issue by Zensse** [TheDutchMC/SkinFixer#16]
06.07 05:46:06 [Server] Server thread/INFO dfosdfosjofssdf issued server command: /setskin 411919
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/INFO [05:46:07][DEBUG][HttpLib] HttpRequest: GET::https://skinfixer.k8s.array21.dev/generate/url/QW5kcmVhYm9iZQ==
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/INFO [05:46:07][DEBUG][HttpLib] HttpRequest: 500::Internal Server Error
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/INFO [05:46:07][DEBUG][HttpLib] HttpRequest ErrorStream: 
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/INFO MineSkin Error
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN java.io.IOException: Server returned HTTP response code: 500 for URL: https://skinfixer.k8s.array21.dev/generate/url/QW5kcmVhYm9iZQ==?
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at nl.thedutchmc.httplib.Http.makeRequest(Http.java:104)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at nl.thedutchmc.SkinFixer.apis.SkinFixerApi.getSkin(SkinFixerApi.java:24)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at nl.thedutchmc.SkinFixer.changeSkin.SkinChangeHandler$1.run(SkinChangeHandler.java:46)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN at java.base/java.lang.Thread.run(Thread.java:831)
06.07 05:46:07 [Server] Craft Scheduler Thread - 97/WARN The SkinFixer API returned an unexpected result: Internal Server Error

**Comment by TheDutchMC** [comment]
Looking at the server logs, while I don't exactly know which errors come from your request, I see the following a lot:
```
MineSkinError: 'MineskinResponse { data: None, error: None }': '"{\"success\":false,\"errorType\":\"GeneratorError\",\"errorCode\":\"invalid_image_url\",\"error\":\"Failed to find image from url\",\"nextRequest\":1625549625.859}"'
MineSkinError: MineskinError { error: "invalid url", error_code: None, next_request: None, delay: None }
```

Decoding the following url: `https://skinfixer.k8s.array21.dev/generate/url/QW5kcmVhYm9iZQ==` gives `Andreabobe` for the URL, I'm guessing that is supposed to be a username? It shouldn't be going via the image channel then, odd

**Comment by TheDutchMC** [comment]
Just checking, which version of SkinFixer are you using? By the looks of it. you're using a version pre v1.7.0, (`dfosdfosjofssdf issued server command: /setskin 411919`, this is the old command structure). Only SkinFixer v1.7.0+ supports setting a skin by username

**Comment by Zensse** [comment]
We are using 1.5.1 on the server, the error only occurs in non premium users, for premium users we have no problem

**Comment by TheDutchMC** [comment]
Odd that it works at all, it shouldn't be working I think since I didn't add that.

Try switching to v1.7.0 (make sure you read the update guide :D), and let me know how that goes :D

**Comment by TheDutchMC** [comment]
Closing due to inactivity from OP
