### ISSUE TITLE
It doesn't work atall?

### ISSUE THREAD

**Issue by uwuzochhi** [TheDutchMC/SkinFixer#18]
I installed the plugin, tried all the commands none of them work, please tell me why.

**Comment by TheDutchMC** [comment]
That's definitely odd.
- What version of SkinFixer are you using?
- What OS and architecture are you on?
- Do you see any errors?

Thanks!

**Comment by uwuzochhi** [comment]
Version: 1.7.1
OS : Windows 10
Errors: Could not load 'plugins/SkinFixer-1.7.1-RELEASE.jar' in folder 'plugins'
17.08 07:39:15 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: dev/array21/skinfixer/SkinFixer has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
17.08 07:39:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-786]
17.08 07:39:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-786]
17.08 07:39:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-786]
17.08 07:39:15 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-786]
17.08 07:39:15 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-786]
17.08 07:39:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-786]
17.08 07:39:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
17.08 07:39:15 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
17.08 07:39:15 [Server] INFO Caused by: java.lang.UnsupportedClassVersionError: dev/array21/skinfixer/SkinFixer has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by TheDutchMC** [comment]
That would be your issue. SkinFixer 1.7.0+ if I remember correctly only support Java 16 and higher. I recommend you upgrade your Java version :smiling_face_with_tear:

**Comment by TheDutchMC** [comment]
Closing due to inactivity
