### ISSUE TITLE
Issue with the new v1.7.2 for MC 1.18 release

### ISSUE THREAD

**Issue by jejeath** [TheDutchMC/SkinFixer#20]
I tried using the plugin with the new 1.18 realese for Minecraft. I'm using a server host, so it's not my pc. The host's OS is a Linux 5.11.0-1021-oracle (aarch64).
It's my first time trying a server with plugins, so it could be me who's wrong. I followed the host's tutorial, and used the new paper 1.18. I was able to use other plugin, but not the SkinFixer.
When the server starts up, it says the following:

[19:51:49 INFO]: [SkinFixer] Enabling SkinFixer v1.7.2
[19:51:49 INFO]: [SkinFixer] Welcome to SkinFixer version 1.7.2 by TheDutchMC!
[19:51:49 WARN]: [SkinFixer] Failed to load libskinfixer. Please open an issue at https://github.com/TheDutchMC/SkinFixer/issues and include your OS, architecture and SkinFixer version. Thanks!
[19:51:49 WARN]: [SkinFixer] java.lang.UnsatisfiedLinkError: /tmp/libskinfixer5653367785927565878/libskinfixer.so: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/libskinfixer5653367785927565878/libskinfixer.so)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at SkinFixer-1.7.2-RELEASE.jar//dev.array21.skinfixer.storage.LibWrapper.<clinit>(LibWrapper.java:66)
        at SkinFixer-1.7.2-RELEASE.jar//dev.array21.skinfixer.SkinFixer.onEnable(SkinFixer.java:55)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:565)
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:479)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:726)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1201)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:833)

[19:51:49 INFO]: [SkinFixer] libskinfixer loaded.
[19:51:49 ERROR]: Error occurred while enabling SkinFixer v1.7.2 (Is it up to date?)
java.lang.UnsatisfiedLinkError: 'void dev.array21.skinfixer.storage.LibSkinFixer.init(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)'
        at dev.array21.skinfixer.storage.LibSkinFixer.init(Native Method) ~[SkinFixer-1.7.2-RELEASE.jar:?]
        at dev.array21.skinfixer.storage.LibWrapper.init(LibWrapper.java:137) ~[SkinFixer-1.7.2-RELEASE.jar:?]
        at dev.array21.skinfixer.SkinFixer.onEnable(SkinFixer.java:56) ~[SkinFixer-1.7.2-RELEASE.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.18.jar:git-Paper-22]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:726) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:51:49 INFO]: [SkinFixer] Disabling SkinFixer v1.7.2

**Comment by TheDutchMC** [comment]
Hey there, thanks for reaching out.

This is likely a fault of my own, I'll see if I can fix this today!

**Comment by jejeath** [comment]
Thanks, man! Appreciate it!

**Comment by TheDutchMC** [comment]
Fixed in v1.7.3
