### ISSUE TITLE
Command bug

### ISSUE THREAD

**Issue by rakzoser** [TheDutchMC/SkinFixer#29]
If I type /skin set "and every letter, only 1" i'll get the error
<img width="368" alt="image" src="https://user-images.githubusercontent.com/82242062/146807222-d730b349-7341-473a-ae76-e77339900ecb.png">
org.bukkit.command.CommandException: Unhandled exception executing command 'skin' in plugin SkinFixer v1.7.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2269) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2080) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2061) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1415) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1393) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1386) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1364) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-21]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "r"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.math.BigInteger.<init>(BigInteger.java:536) ~[?:?]
        at java.math.BigInteger.<init>(BigInteger.java:674) ~[?:?]
        at dev.array21.skinfixer.commands.subcommands.SetCommand.isValidInt(SetCommand.java:78) ~[SkinFixer-1.7.4-RELEASE.jar:?]
        at dev.array21.skinfixer.commands.subcommands.SetCommand.onSubcommand(SetCommand.java:32) ~[SkinFixer-1.7.4-RELEASE.jar:?]
        at dev.array21.skinfixer.commands.CommandHandler.onCommand(CommandHandler.java:75) ~[SkinFixer-1.7.4-RELEASE.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more

**Version information (please complete the following information):**
 - Minecraft version: [1.18.1]
 - SkinFixer version: [1.7.4]
 - Operating system and OS version: [Windows 10]
 - Architecture: [64]

**Comment by TheDutchMC** [comment]
Interesting, seems I forgot to do input validation. Thanks for reporting!
