### ISSUE TITLE
Exception on start

### ISSUE THREAD

**Issue by Giampli** [TheDutchMC/SkinFixer#3]
**Describe the bug**
When the server start it throws an exception when initializing Discord API

**To Reproduce**
1. Start server
2. Exception thrown

**Expected behavior**
Not throw an exception

**Additional context**
StackTrace:

> 01.11 00:17:36 [Server] INFO java.lang.NoClassDefFoundError: net/dv8tion/jda/api/entities/MessageChannel
> 01.11 00:17:36 [Server] INFO at nl.thedutchmc.SkinFixer.SkinFixer.onEnable(SkinFixer.java:47) ~[?:?]
> 01.11 00:17:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
> 01.11 00:17:36 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.api.entities.MessageChannel
> 01.11 00:17:36 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_211]
> 01.11 00:17:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[Spigot_Latest.jar:git-Spigot-57bbdd8-dea4138]
> 01.11 00:17:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
> 01.11 00:17:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
> 01.11 00:17:36 [Server] INFO ... 11 more

**Comment by TheDutchMC** [comment]
Ai. Thanks for reporting!

What version of SkinFixer are you using?

**Comment by TheDutchMC** [comment]
Cannot reproduce with version v1.1

**Comment by Giampli** [comment]
I'm using version 1.1 on the latest Spigot release

**Comment by TheDutchMC** [comment]
That is definitely odd. What OS are you running?

**Comment by TheDutchMC** [comment]
Closing due to inactivity
