### ISSUE TITLE
Skins are not fetched anymore and HTTP error 400 is returned

### ISSUE THREAD

**Issue by Eric-01** [TheDutchMC/SkinFixer#6]
**Describe the bug**
For a few days now, every time someone joins my server, their skin is not fetched anymore (if they joined using a "premium" account), and warnings are printed in the server console (shown in the "Additional context" section below).

**To Reproduce**
1. Launch Minecraft.
2. Join a server that has SkinFixer plugin installed.
3. Observe that your skin is not fetched anymore (if you joined using a "premium" account), and warnings are printed in the server console.

**Expected behavior**
The plugin should work correctly as before.

**Environment**
* Minecraft version: 1.16.5
* Paper build: #634 for MC 1.16.5
* SkinFixer version: 1.3.1

**Additional context**
The following warnings are printed in the server console:
```
[20:20:15 WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mojang.com/profiles/minecraft
[20:20:15 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
[20:20:15 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[20:20:15 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
[20:20:15 WARN]: 	at nl.thedutchmc.httplib.Http.makeRequest(Http.java:104)
[20:20:15 WARN]: 	at nl.thedutchmc.SkinFixer.apis.MojangApi.getUuidFromMojang(MojangApi.java:23)
[20:20:15 WARN]: 	at nl.thedutchmc.SkinFixer.minecraftevents.PlayerJoinEventListener$1.run(PlayerJoinEventListener.java:27)
[20:20:15 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:20:15 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:20:15 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:20:15 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:20:15 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:20:15 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[20:20:15 WARN]: [SkinFixer] The Mojang API returned an unexpected result: Bad Request
[20:20:15 WARN]: [SkinFixer] Something went wrong fetching the UUID from Mojang.
```

**Comment by TheDutchMC** [comment]
THey probably updated their API. Will look into this ASAP! Thanks for reporting! :D

**Comment by TheDutchMC** [comment]
Before changing code I'll be awaiting [this](https://bugs.mojang.com/projects/WEB/issues/WEB-4457?filter=allopenissues) issue on the mojang bug tracker

**Comment by Eric-01** [comment]
Thank you for letting me know that this may be an upstream issue.

**Comment by Eric-01** [comment]
Thank you for letting me know that it may be an upstream issue.

**Comment by TheDutchMC** [comment]
The issue should be resolved now! :D

**Comment by Eric-01** [comment]
I confirm that it works again. Do you know if they've broken it accidentally, or maybe they are planning to deprecate and then remove the current methods in favor of new ones (just guessing)?

**Comment by TheDutchMC** [comment]
I'm guessing it was just broken :D (Hopefully, anyways)

If they do decide to deprecate it, I'll make sure to update the plugin with a new endpoint, if there is any :D

**Comment by Eric-01** [comment]
Thank you for letting me know.
