### ISSUE TITLE
is show "bad requset" every code skin

### ISSUE THREAD

**Issue by kristza** [TheDutchMC/SkinFixer#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Minecraft version: [e.g. 1.16.2]
 - SkinFixer version: [e.g. 1.0]

**Additional context**

**Comment by TheDutchMC** [comment]
Hey there, thanks for your report!

Would you be able to provide some more details please?

**Comment by kristza** [comment]
i type /setskin nuber but is show "bad request" every code
i use code in /getcode

**Comment by TheDutchMC** [comment]
Could you send a stacktrace please? (All errors in the console)

**Comment by kristza** [comment]
[18:37:56] [Craft Scheduler Thread - 7/INFO]: [18:37:56][DEBUG][HttpLib] HttpRequest: POST::https://api.mineskin.org/generate/url
[18:37:56] [Craft Scheduler Thread - 7/INFO]: [18:37:56][DEBUG][HttpLib] HttpRequest: 400::Bad Request
[18:37:56] [Craft Scheduler Thread - 7/INFO]: [18:37:56][DEBUG][HttpLib] HttpRequest ErrorStream:
[18:37:56] [Craft Scheduler Thread - 7/INFO]: {"error":"invalid url"}
[18:37:56] [Craft Scheduler Thread - 7/WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mineskin.org/generate/url?User-Agent=SkinFixer&url=CHIcKYKunG
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at nl.thedutchmc.httplib.Http.makeRequest(Http.java:104)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at nl.thedutchmc.SkinFixer.apis.MineskinApi.getSkin(MineskinApi.java:30)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at nl.thedutchmc.SkinFixer.changeSkin.SkinChangeHandler$1.run(SkinChangeHandler.java:47)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[18:37:56] [Craft Scheduler Thread - 7/WARN]:   at java.base/java.lang.Thread.run(Thread.java:831)
[18:37:56] [Craft Scheduler Thread - 7/WARN]: [SkinFixer] The MineSkin API returned an unexpected result: Bad Request

**Comment by TheDutchMC** [comment]
It seems MineSkin has significantly changed their API. I'll rework SkinFixer to support it.

**Comment by kristza** [comment]
thank you

**Comment by TheDutchMC** [comment]
Fixed in [v1.5.1](https://github.com/TheDutchMC/SkinFixer/releases/tag/1.5.1)
